# -*- coding: utf-8 -*-
"""LASSO+XGBoost

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Yr8clsnqPWi5rrd_jP9tGEqramBwlDt

Input CSV 제작
"""

import numpy as np
import pandas as pd
dic={"PAT":[],"PTT":[],"weight":[],"height":[],"age":[], "gender":[]}
dic["PAT"].append(float(input("PAT(ms):")))
dic["PTT"].append(float(input("PTT(ms):")))
dic["weight"].append(float(input("weight(kg):")))
dic["height"].append(float(input("height(cm):")))
dic["age"].append(int(input("age(만 나이):")))
dic["gender"].append(int(input("gender(남성: 1, 여성: 0):")))
df = pd.DataFrame(dic)
df.to_csv("test.csv",index= False)

df=pd.read_csv("dataset(jump_100).csv")
df=df.drop(columns=["subject_id", "filename","sbp (mmHg)","dbp  (mmHg)"])
df.to_csv("test.csv",index=False)

"""**초기화**"""

from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Lasso
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.linear_model import LassoCV
from sklearn.metrics import mean_squared_error
from random import randint
import math as m
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd



def fit_hybrid(X_tr, y_tr, random_seed):
    alphas = [LassoMinAlpha * (LassoAlphaMultiplier ** i) for i in range(LassoRepetition)]

    lasso = LassoCV(alphas=alphas, cv=LassoVerification, max_iter=Lassomax_iter, tol=Lassotol)
    lasso.fit(X_tr, y_tr)

    residuals = y_tr - lasso.predict(X_tr)

    xgb = RandomizedSearchCV(
      estimator=XGBRegressor(tree_method='hist', random_state=random_seed),
      param_distributions=XG_param_grid,
      n_iter=XG_iteration,
      cv=XG_cv,
      scoring=XG_scoring,
      n_jobs=-1,
      random_state=random_seed,
      )

    xgb.fit(X_tr, residuals)

    return lasso, xgb

def predict_hybrid(lasso, xgb, X_sc):
    return lasso.predict(X_sc) + xgb.predict(X_sc)

def compute_metrics(y_true, y_pred):
    mse   = mean_squared_error(y_true, y_pred)
    mae   = mean_absolute_error(y_true, y_pred)
    r2    = r2_score(y_true, y_pred)
    erate = np.abs((y_true - y_pred) / y_true * 100)
    return mse, mae, r2, float(np.max(erate)), float(np.mean(erate)), erate

def _scatter(ax, y_true, y_hat, title='Actual vs. Predicted'):
    # 1. 평가지표 계산
    mse = mean_squared_error(y_true, y_hat)
    mae = mean_absolute_error(y_true, y_hat)
    r2 = r2_score(y_true, y_hat)

    # 2. 원본 산점도 및 대각선 그리기
    ax.scatter(y_true, y_hat, color='teal', alpha=0.7, label='Hybrid Model (Lasso+XGB)')
    lo = min(y_true.min(), y_hat.min())
    hi = max(y_true.max(), y_hat.max())
    ax.plot([lo, hi], [lo, hi], color='crimson',
            linestyle='--', lw=2, label='Perfect Prediction')


    stats_text = (
        f"MSE = {mse:.2f}\n"
        f"MAE = {mae:.2f}\n"
        f"R² = {r2:.2f}"
    )

    # transform=ax.transAxes를 사용하여 축 기준 상대 좌표(0~1)로 위치를 잡습니다.
    # 좌상단 여백(x=0.05, y=0.95)에 배치합니다.
    ax.text(
        0.05, 0.95, stats_text,
        transform=ax.transAxes,
        fontsize=11,
        verticalalignment='top',
        horizontalalignment='left',
        bbox=dict(
            boxstyle='round,pad=0.5',  # 둥근 모서리와 내부 여백(Padding)
            facecolor='white',         # 박스 배경색
            edgecolor='darkgray',      # 테두리 색상
            alpha=0.9                  # 불투명도
        )
    )

    # 4. 축 및 타이틀 레이블 설정
    ax.set_xlabel('Actual', fontsize=12)
    ax.set_ylabel('Predicted', fontsize=12)
    ax.set_title(title, fontsize=13)

    # 5. 범례 및 그리드 설정
    # 지표 박스가 좌상단에 있으므로, 범례(Legend)는 우하단(lower right)으로 보냅니다.
    ax.legend(loc='lower right')
    ax.grid(True, linestyle=':', alpha=0.6)


def _feature_importance(ax, importances, feature_names, title='Feature Importance(only XGBoost)', color='teal'):
    cleaned_names = [name.replace('sbp (mmHg)', 'sbp').replace('dbp  (mmHg)', 'dbp') for name in feature_names]

    df = pd.DataFrame({
        'feature': cleaned_names,
        'importance': importances
    }).sort_values(by='importance', ascending=True)

    ax.barh(df['feature'], df['importance'], color=color, edgecolor='none', height=0.75)

    ax.set_title(title, fontsize=13, pad=15)
    ax.set_xlabel('importance', fontsize=11, labelpad=8)
    ax.set_ylabel('feature', fontsize=11, labelpad=8)

    ax.set_xlim(0, max(importances) * 1.05)

    ax.tick_params(axis='both', labelsize=10)
    ax.grid(False)

    for spine in ax.spines.values():
        spine.set_edgecolor('#d3d3d3')
        spine.set_linewidth(0.8)

def _hist(ax, err, title='Error Rate Distribution'):
    bins = np.arange(0, 40, 1)
    ax.hist(err, bins=bins, color='skyblue', edgecolor='black', alpha=0.8)

    mean_err = np.mean(err)
    ax.axvline(mean_err, color='red', linewidth=2, label=f'Mean: {mean_err:.2f}%')

    outliers_count = np.sum(err >= 40)

    stats_text = f"Outliers (≥40%) = {outliers_count}"

    ax.text(
        0.95, 0.95, stats_text,
        transform=ax.transAxes,
        fontsize=11,
        verticalalignment='top',
        horizontalalignment='right', # 우측 정렬
        bbox=dict(
            boxstyle='round,pad=0.5',  # 부드러운 라운드 테두리
            facecolor='white',         # 흰색 배경
            edgecolor='darkgray',      # 테두리 색상
            alpha=0.9                  # 불투명도
        )
    )
    ax.set_xticks(np.arange(0, 41, 5))

    ax.set_xlabel('Error Rate (%)'); ax.set_ylabel('Frequency')
    ax.set_title(title); ax.grid(axis='y', alpha=0.3)
    ax.legend(loc='upper left')

def augment_tabular_data(df, n_iterations, method='dynamic_gaussian'):
    df = df.copy()
    df.columns = df.columns.str.strip()
    orig_dtypes = df.dtypes
    col_stds = df.std(numeric_only=True)

    # 성별 등 범주형 제외 (수치형 피처만 증강 대상)
    features_to_augment = [col for col in df.columns if col != 'gender']
    augmented_rows = []

    for _ in range(n_iterations):
        if method == 'dynamic_gaussian':
            sampled_row = df.sample(n=1).iloc[0].copy()
            volatility = np.random.uniform(0.01, 0.06)

            for col in features_to_augment:
                if np.random.rand() < 0.6:  # 60% 확률로 피처에 변형 가함
                    noise = np.random.normal(0, col_stds[col] * volatility)
                    sampled_row[col] = sampled_row[col] + noise

        elif method == 'mixup':
            row1 = df.sample(n=1).iloc[0].copy()
            row2 = df.sample(n=1).iloc[0].copy()
            lam = np.random.uniform(0.4, 0.6)

            sampled_row = row1.copy()
            for col in features_to_augment:
                sampled_row[col] = lam * row1[col] + (1 - lam) * row2[col]

        for col in features_to_augment:
            if np.issubdtype(orig_dtypes[col], np.integer):
                sampled_row[col] = np.round(sampled_row[col])
            elif np.issubdtype(orig_dtypes[col], np.floating):
                sampled_row[col] = np.round(sampled_row[col], 2)

        augmented_rows.append(sampled_row)

    df_augmented = pd.DataFrame(augmented_rows)
    df_result = pd.concat([df, df_augmented], ignore_index=True)

    for col in df.columns:
        df_result[col] = df_result[col].astype(orig_dtypes[col])

    return df_result

"""**모델 실행 코드**"""

#data refining
filename=100

#Main_setting
trial      = 1 # iteration of model testing
TestSize   = 0.2 # split ratio
dataAug = 1 #augmentation raatio(eg: dataAug = 2.2 --> augment 2.2*(size of dataset) data in dataset)
CSVname    = f'cleancsv_{str(filename)}.csv'
targetvar  = 'sbp (mmHg)'
targetvar2 = 'dbp  (mmHg)'
mode       = 0         # 0 = predict only, 1 = internal split, 2 = external test CSV with labels
# mode = 0 에서는 예측한 데이터가 predicted_csv로 저장됨
testCSV    = "test.csv"
image      = False       # save / show plots

#Lasso_setting
LassoMinAlpha        = 1e-4
LassoAlphaMultiplier = 2
LassoRepetition      = 5

#Lasso but unnecessary to be changed
LassoVerification  = 5 #cv of Lasso
Lassomax_iter = 50000
Lassotol = 0.01


#XGBoost_setting
XG_param_grid = {
    'n_estimators':  [50, 100, 200, 300],
    'learning_rate': [0.01, 0.03, 0.05],
    'max_depth':     [2, 3, 4],
    'subsample':     [0.6, 0.7, 0.8],
    'colsample_bytree': [0.7, 0.8, 1.0],
    'reg_alpha':     [0, 0.1, 1.0],
    'reg_lambda':    [1.0, 5.0, 10.0]
}
XG_cv= 3
XG_iteration = 20
XGscoringlist=['neg_mean_squared_error',
              'neg_mean_absolute_error',
              'neg_root_mean_squared_error',
              'r2',
              'neg_median_absolute_error',
              'neg_mean_absolute_percentage_error']
XG_scoring = XGscoringlist[1]

#error in internal_split
error_rate = 5.7461
error_rate2 = 9.8147

#Graph size
fig_w, fig_h = 26, 10

################################################################################################################################################################################################3


lmse,  lmae,  lr2,  lmax,  lmean  = [], [], [], [], []
lmse2, lmae2, lr22, lmax2, lmean2 = [], [], [], [], []

with open(f"{filename}.txt", "w", encoding='utf-8') as f:
  for attempt in range(trial):
    seed = attempt + 1

    df = pd.read_csv(CSVname)
    df.columns = df.columns.str.strip()

    drop_cols = [targetvar, targetvar2]

#SBP
    if mode == 1:
      # 1. 원본 상태에서 완전히 독립적인 Train / Test 데이터프레임으로 선분할
      df_train, df_test = train_test_split(df, test_size=TestSize, random_state=42)

      # 2. 🔥 핵심: 분할된 train_df만 가우시안 증강 함수에 주입 (테스트셋은 절대 보지 못함)
      aug_size = int(len(df_train) * dataAug)
      df_train_aug = augment_tabular_data(df_train, n_iterations=aug_size, method='mixup')

      X_train = df_train_aug.drop(columns=drop_cols)
      y_train = df_train_aug[targetvar]

      X_test = df_test.drop(columns=drop_cols)
      y_test = df_test[targetvar]
    else:
      # 외부 테스트 및 예측 모드: 전체 데이터를 기반으로 훈련셋 증강 수행
      aug_size = int(len(df_train) * dataAug)
      df_aug = augment_tabular_data(df, n_iterations=aug_size, method='mixup')
      X_train = df_aug.drop(columns=drop_cols)
      y_train = df_aug[targetvar]

      testing_data = pd.read_csv(testCSV)
      testing_data.columns = testing_data.columns.str.strip()
      if mode == 2:
        X_test = testing_data.drop(columns=[targetvar, targetvar2], errors='ignore')
        y_test = testing_data[targetvar]
      else:                   # mode == 0  (pure prediction, no labels)
        X_test = testing_data.drop(columns=drop_cols, errors='ignore')
        y_test = None

    # 스케일링 적용 (기존 구조 보존)
    scaler = StandardScaler()
    X_train_sc = scaler.fit_transform(X_train)
    X_test_sc  = scaler.transform(X_test)

    #학습
    lasso1, xgb1 = fit_hybrid(X_train_sc, y_train, seed)
    y_pred = predict_hybrid(lasso1, xgb1, X_test_sc)

#DBP
    if mode > 0:
      mse, mae, r2, maxima, meania, erate = compute_metrics(y_test, y_pred)

    if mode == 1:
      df_train2, df_test2 = train_test_split(df, test_size=TestSize, random_state=42)
      aug_size = int(len(df_train) * dataAug)
      df_train2_aug = augment_tabular_data(df_train2, n_iterations=aug_size, method='mixup')

      X2_train = df_train2_aug.drop(columns=drop_cols)
      y2_train = df_train2_aug[targetvar2]

      X2_test = df_test2.drop(columns=drop_cols)
      y2_test = df_test2[targetvar2]
    else:
      X2_train = df_aug.drop(columns=drop_cols)
      y2_train = df_aug[targetvar2]
      if mode == 2:
          X2_test  = testing_data.drop(columns=[targetvar, targetvar2], errors='ignore')
          y2_test  = testing_data[targetvar2]
      else:
          X2_test  = X_test
          y2_test  = None

    #스케이링
    scaler2 = StandardScaler()
    X2_train_sc = scaler2.fit_transform(X2_train)
    X2_test_sc  = scaler2.transform(X2_test)

    #학습
    lasso2, xgb2 = fit_hybrid(X2_train_sc, y2_train, seed + 1000)
    y2_pred = predict_hybrid(lasso2, xgb2, X2_test_sc)

    if mode > 0:
        mse2, mae2, r22, maxima2, meania2, erate2 = compute_metrics(y2_test, y2_pred)

#image
    if mode > 0 and image:
      n_rows = 2
      fig, axes = plt.subplots(n_rows, 3, figsize=(fig_w, fig_h * n_rows))
      if n_rows == 1:
          axes = axes[np.newaxis, :]

      feature_cols = ['weight', 'height', 'gender', 'age', 'PAT', 'PTT']
      _scatter(axes[0, 0], y_test,  y_pred,  f'SBP – Actual vs Predicted')
      # _heatmap(axes[0, 1])
      _feature_importance(axes[0, 1], xgb1.best_estimator_.feature_importances_, feature_cols, f'SBP – Feature Importance(Only XGBoost)', color='teal')
      _hist   (axes[0, 2], erate,            f'SBP – Error Rate Distribution')

      _scatter(axes[1, 0], y2_test, y2_pred, f'DBP – Actual vs Predicted')
      # _heatmap(axes[1, 1])
      _feature_importance(axes[1, 1], xgb2.best_estimator_.feature_importances_, feature_cols, f'DBP – Feature Importance(Only XGBoost)', color='skyblue')
      _hist   (axes[1, 2], erate2,           f'DBP – Error Rate Distribution')

      plt.tight_layout()
      file_name = f"{filename}_{attempt + 1}.png"
      plt.savefig(file_name, dpi=300, bbox_inches='tight')
      plt.show()
      plt.close(fig)

#Prediction mode
    if mode == 0:
      out_df = pd.read_csv(testCSV)
      y_pred = np.round(y_pred).astype(int)
      out_df[targetvar] = y_pred

      y2_pred = np.round(y2_pred).astype(int)
      out_df[targetvar2] = y2_pred

      out_df.to_csv("predicted.csv", index=False)
      print(f"Predictions saved to predicted.csv")
      print(f"Expected errors sbp:{error_rate}%, dbp={error_rate2}%")
      continue

#
    output = (
        f"--- Trial {attempt + 1} ---\n"
        f"MSE-1  : {mse:.4f}\n"
        f"MAE-1  : {mae:.4f}\n"
        f"R2-1   : {r2:.4f}\n"
        f"Max err-1  : {maxima:.4f}%\n"
        f"Mean err-1 : {meania:.4f}%\n"
        f"Outliers (≥40%)-1: {int(np.sum(erate >= 40))}\n\n"
    )
    print(output); f.write(output)

    lmse.append(mse); lmae.append(mae); lr2.append(r2)
    lmax.append(maxima); lmean.append(meania)

    output2 = (
        f"MSE-2  : {mse2:.4f}\n"
        f"MAE-2  : {mae2:.4f}\n"
        f"R2-2   : {r22:.4f}\n"
        f"Max err-2  : {maxima2:.4f}%\n"
        f"Mean err-2 : {meania2:.4f}%\n"
        f"Outliers (≥40%)-2: {int(np.sum(erate2 >= 40))}\n\n"
    )
    print(output2); f.write(output2)

    lmse2.append(mse2); lmae2.append(mae2); lr22.append(r22)
    lmax2.append(maxima2); lmean2.append(meania2)

  if mode > 0 and lmse:
      summary = (
          "\n=== Summary ===\n"
          f"Avg MSE-1  : {np.mean(lmse):.4f}\n"
          f"Avg MAE-1  : {np.mean(lmae):.4f}\n"
          f"Avg R2-1   : {np.mean(lr2):.4f}\n"
          f"Worst max err-1  : {max(lmax):.4f}%\n"
          f"Avg mean err-1   : {np.mean(lmean):.4f}%\n"
          f"std mean err-1 : {np.std(lmean):.4f}%\n"
      )
      print(summary); f.write(summary)

      summary2 = (
          f"Avg MSE-2  : {np.mean(lmse2):.4f}\n"
          f"Avg MAE-2  : {np.mean(lmae2):.4f}\n"
          f"Avg R2-2   : {np.mean(lr22):.4f}\n"
          f"Worst max err-2  : {max(lmax2):.4f}%\n"
          f"Avg mean err-2   : {np.mean(lmean2):.4f}%\n"
          f"std mean err-2 : {np.std(lmean2):.4f}%\n"
      )
      print(summary2); f.write(summary2)

"""Mode=2(타 train dataset 평가) train dataset 정렬 함수"""

df = pd.read_csv(testCSV)
df = df.drop(columns="subject_id")
df={'gender': df["gender"], 'age': df['age'], 'height': df['height'], 'weight': df['weight'], 'PAT': df['PAT'], 'PTT':df['PTT'], 'sbp (mmHg)' : df['sbp'], 'dbp  (mmHg)': df['dbp']}
df = pd.DataFrame(df)
df.to_csv("test.csv",index= False)