# -*- coding: utf-8 -*-
"""RF(윤지,수민).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DlGTDCfmH_l34tChzPdWCFJ96L0s7F2x
"""

!pip install optuna

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import optuna
import warnings

from sklearn.model_selection import LeaveOneGroupOut, cross_val_predict
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import RobustScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, mean_absolute_percentage_error

# Optuna 로그 간소화 (진행률만 깔끔하게 보기)
optuna.logging.set_verbosity(optuna.logging.WARNING)
warnings.filterwarnings('ignore')

"""# 1. 설정 (나중에 여기만 수정)"""

CONFIG = {
    'train_path': 'U_dataset_3rd_60.csv', # 원본 학습 데이터 경로

    'feature_cols': ['PAT', 'PTT', 'gender', 'age', 'height', 'weight'],
    'target_sbp': 'sbp',
    'target_dbp': 'dbp',
    'group_col': 'subject_id',

    'outlier_cols': ['PAT', 'PTT'],
    'iqr_multiplier': 5.0,  # 3.0이면 극단적인 이상치만 제거 (데이터가 적을땐 값을 키워 기준 완화)
    'n_trials': 100          # Optuna가 튜닝을 시도할 횟수
}

"""# 2. 이상치 제거, 시각화 함수"""

def remove_outliers(df, cols, multiplier):
    df_clean = df.copy()
    for col in cols:
        if col not in df_clean.columns: continue
        Q1, Q3 = df_clean[col].quantile(0.25), df_clean[col].quantile(0.75)
        IQR = Q3 - Q1
        df_clean = df_clean[(df_clean[col] >= Q1 - multiplier * IQR) &
                            (df_clean[col] <= Q3 + multiplier * IQR)]
    return df_clean

def style_ax(ax, text='#222222', gray='#555555', bg='white'):
    ax.set_facecolor(bg)
    ax.tick_params(colors=text, labelsize=9)
    ax.spines[:].set_color('#cccccc')
    ax.title.set_color(text)
    ax.title.set_fontweight('bold')
    ax.xaxis.label.set_color(gray)
    ax.yaxis.label.set_color(gray)

"""# 3. 메인 실행부"""

if __name__ == "__main__":

    # 1. 데이터 로드
    train_data = pd.read_csv(CONFIG['train_path'])

    # 컬럼명 오류 방지를 위해 원본 컬럼명 통일 처리
    if 'sbp (mmHg)' in train_data.columns:
        train_data.rename(columns={'sbp (mmHg)': 'sbp', 'dbp  (mmHg)': 'dbp'}, inplace=True)

    # PAT, PTT 값 없는 행 삭제
    train_data = train_data.dropna(subset=['PAT', 'PTT'])

    # 불필요한 컬럼 삭제
    # 1. 'test num' 명시적 삭제
    if 'test num' in train_data.columns:
        train_data = train_data.drop(columns=['test num'])

    # 2. 마지막 컬럼 자동 삭제 (컬럼 이름과 상관없이 맨 끝 컬럼 날리기)
    train_data = train_data.iloc[:, :-1]

    train_clean = remove_outliers(train_data, CONFIG['outlier_cols'], CONFIG['iqr_multiplier'])

    X_train = train_clean[CONFIG['feature_cols']]
    y_sbp_train = train_clean[CONFIG['target_sbp']]
    y_dbp_train = train_clean[CONFIG['target_dbp']]
    groups_train = train_clean[CONFIG['group_col']]

    print('=' * 55)
    print(f"학습 데이터  : {len(train_clean)} 줄 (이상치 제거 완료)")
    print(f"학습 피험자수: {groups_train.nunique()} 명")
    print('=' * 55)

"""# 4. 옵튜나 튜닝(최적의 하이퍼파라미터 찾기, sbp/dbp 따로 진행)"""

def objective_sbp(trial, X, y, groups):
        # 1. 튜닝할 하이퍼파라미터 후보군
        params = {
                'n_estimators': trial.suggest_int('n_estimators', 50, 150),
                'max_depth': trial.suggest_int('max_depth', 2, 5),
                'min_samples_split': trial.suggest_int('min_samples_split', 4, 10),
                'min_samples_leaf': trial.suggest_int('min_samples_leaf', 2, 5),
                'random_state': 42,
                'n_jobs': -1
        }

        # 2. RobustScaler + Random Forest 파이프라인
        model = make_pipeline(RobustScaler(), RandomForestRegressor(**params))

        # 3. LeaveOneGroupOut
        cv = LeaveOneGroupOut()

        # 4. 모의고사 실행 및 채점
        scores = []
        for train_idx, val_idx in cv.split(X, y, groups):

            # [Step A: 원본 분할]
            X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]
            y_tr, y_val = y.iloc[train_idx], y.iloc[val_idx]

            # [Step B: 학습]
            model.fit(X_tr, y_tr)

            # [Step C: 채점] 깨끗한 원본 시험지로 예측 및 오차 계산
            preds = model.predict(X_val)
            scores.append(mean_absolute_error(y_val, preds))

        return np.mean(scores)

def objective_dbp(trial, X, y, groups):
    # 1. 튜닝할 하이퍼파라미터 후보군 (DBP는 똑똑해지면 과적합)
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 50, 100),
        'max_depth': trial.suggest_int('max_depth', 1, 3),
        'min_samples_split': trial.suggest_int('min_samples_split', 6, 12), # 가지치기 조건 강화 (기존 4~10)
        'min_samples_leaf': trial.suggest_int('min_samples_leaf', 4, 8),    # 잎사귀에 최소 4~8명을 남김 (기존 2~5)
        'random_state': 42,
        'n_jobs': -1
    }

    # 2. RobustScaler + Random Forest 파이프라인
    model = make_pipeline(RobustScaler(), RandomForestRegressor(**params))

    # 3. LeaveOneGroupOut
    cv = LeaveOneGroupOut()

    # 4. 모의고사 실행 및 채점
    scores = []
    for train_idx, val_idx in cv.split(X, y, groups):
        X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_tr, y_val = y.iloc[train_idx], y.iloc[val_idx]

        model.fit(X_tr, y_tr)

        preds = model.predict(X_val)
        scores.append(mean_absolute_error(y_val, preds))

    return np.mean(scores)

print("\n[Optuna] SBP 모델 최적의 파라미터 탐색 중...")
study_sbp = optuna.create_study(direction='minimize') #오차가 제일 작게 나오는 옵션 찾도록 옵튜나에게 명령
study_sbp.optimize(lambda trial: objective_sbp(trial, X_train, y_sbp_train, groups_train), n_trials=CONFIG['n_trials'])

# SBP 튜닝 완료 후
print("="*50)
print(f"[SBP] 찾은 최적의 파라미터: {study_sbp.best_params}")
print(f"[SBP] LOGO 교차검증 최저 오차(MAE): {study_sbp.best_value:.4f}")
print("="*50)

print("[Optuna] DBP 모델 최적의 파라미터 탐색 중...")
study_dbp = optuna.create_study(direction='minimize') #오차가 제일 작게 나오는 옵션 찾도록 옵튜나에게 명령
study_dbp.optimize(lambda trial: objective_dbp(trial, X_train, y_dbp_train, groups_train), n_trials=CONFIG['n_trials'])

# DBP 튜닝 완료 후
print("="*50)
print(f"[DBP] 찾은 최적의 파라미터: {study_dbp.best_params}")
print(f"[DBP] LOGO 교차검증 최저 오차(MAE): {study_dbp.best_value:.4f}")
print("="*50)

"""# 5. 예상 오차율(a, b) 추출을 위한 교차 검증"""

# 찾은 최적의 하이퍼파라미터 기반으로 최적의 모델 세팅
best_model_sbp = make_pipeline(RobustScaler(), RandomForestRegressor(**study_sbp.best_params, random_state=42, n_jobs=-1))
best_model_dbp = make_pipeline(RobustScaler(), RandomForestRegressor(**study_dbp.best_params, random_state=42, n_jobs=-1))

cv = LeaveOneGroupOut()

print("\n[OOF 예측] SBP & DBP 순수 원본 데이터 기반 교차검증 진행 중...")
oof_pred_sbp = cross_val_predict(best_model_sbp, X_train, y_sbp_train, cv=cv, groups=groups_train)
oof_pred_dbp = cross_val_predict(best_model_dbp, X_train, y_dbp_train, cv=cv, groups=groups_train)

# 2. 예상 MAPE(오차율) 계산
a = mean_absolute_percentage_error(y_sbp_train, oof_pred_sbp) * 100
b = mean_absolute_percentage_error(y_dbp_train, oof_pred_dbp) * 100

print(f"[검증 완료] SBP 평균 오차율: {a:.2f}%, DBP 평균 오차율: {b:.2f}%")

# 3. 전체 데이터로 실전 투입용 최종 모델 학습

print("\n[최종 학습] 전체 순수 원본 데이터를 활용하여 실전 투입용 최종 모델을 학습합니다...")
best_model_sbp.fit(X_train, y_sbp_train)
best_model_dbp.fit(X_train, y_dbp_train)

print("\n[완료] 최적 파라미터 기반 100% 원본 데이터 최종 모델 학습 완료!")

"""# 6. 시각화 (산점도, 변수 중요도, 잔차 분포도)"""

# 1) OOF(모의고사) 결과를 환자별(subject_id)로 평균 내어 '점 1개 = 환자 1명'으로 압축
oof_df = pd.DataFrame({
        CONFIG['group_col']: groups_train,
        'Actual_SBP': y_sbp_train,
        'Pred_SBP': oof_pred_sbp,
        'Actual_DBP': y_dbp_train,
        'Pred_DBP': oof_pred_dbp
})
oof_grouped = oof_df.groupby(CONFIG['group_col']).mean()
n_patients = len(oof_grouped) # 시각화에 표시할 환자 수

# 2) 도화지 준비 (1행: 산점도, 2행: 잔차분포도, 3행: 변수중요도)
fig, axes = plt.subplots(3, 2, figsize=(14, 16))
fig.patch.set_facecolor('white')
box_style = dict(boxstyle='round,pad=0.5', facecolor='white', alpha=0.8, edgecolor='gray')

# 3) 산점도 그리기 (SBP, DBP)
targets = [('Actual_SBP', 'Pred_SBP', 'SBP', 0), ('Actual_DBP', 'Pred_DBP', 'DBP', 1)]
for actual, pred, label, col_idx in targets:
  ax = axes[0, col_idx]; style_ax(ax)
  y_true, y_pred = oof_grouped[actual], oof_grouped[pred]

  # 환자 단위 점 찍기
  color = '#E76F51' if label == 'SBP' else '#2A9D8F'
  ax.scatter(y_true, y_pred, color=color, alpha=0.75, s=60, edgecolors='none')

  # 대각선 (정답선)
  lo, hi = min(y_true.min(), y_pred.min()) - 5, max(y_true.max(), y_pred.max()) + 5
  ax.plot([lo, hi], [lo, hi], '--', color='#555555', lw=1.2)
  ax.set_xlim(lo, hi); ax.set_ylim(lo, hi)
  ax.set_title(f'{label} CV Prediction (Validation)')

  # R2, MAE 텍스트 박스 삽입
  r2, mae = r2_score(y_true, y_pred), mean_absolute_error(y_true, y_pred)
  ax.text(0.05, 0.95, f"N = {n_patients} (Patients)\nR² = {r2:.2f}\nMAE = {mae:.2f}",
                transform=ax.transAxes, fontsize=11, verticalalignment='top', bbox=box_style)
  style_ax(ax)

# 4) 잔차분포도 (SBP, DBP)
# 잔차(Residuals) 계산
residual_sbp = oof_pred_sbp - y_sbp_train
residual_dbp = oof_pred_dbp - y_dbp_train

# --- SBP 잔차 막대 그래프 ---
style_ax(axes[1, 0])
axes[1, 0].hist(residual_sbp, bins=30, color='salmon', alpha=0.6, edgecolor='white')
axes[1, 0].axvline(x=0, color='black', linestyle='-', linewidth=2.5, label='Zero Error') # 0 기준선
axes[1, 0].set_title('SBP Residual Distribution', fontweight='bold')
axes[1, 0].set_xlabel('Residuals (Pred - Actual)')
# 평균 오차율 박스 추가
axes[1, 0].text(0.05, 0.95, f"Mean Error Rate\n{a:.2f}%",
                transform=axes[1, 0].transAxes, verticalalignment='top', bbox=box_style)
axes[1, 0].legend()

# --- DBP 잔차 막대 그래프 ---
style_ax(axes[1, 1])
axes[1, 1].hist(residual_dbp, bins=30, color='skyblue', alpha=0.6, edgecolor='white')
axes[1, 1].axvline(x=0, color='black', linestyle='-', linewidth=2.5, label='Zero Error') # 0 기준선
axes[1, 1].set_title('DBP Residual Distribution', fontweight='bold')
axes[1, 1].set_xlabel('Residuals (Pred - Actual)')
# 평균 오차율 박스 추가
axes[1, 1].text(0.05, 0.95, f"Mean Error Rate\n{b:.2f}%",
                transform=axes[1, 1].transAxes, verticalalignment='top', bbox=box_style)
axes[1, 1].legend()

# 5) 변수 중요도 그리기 (전체 데이터로 학습된 최종 모델 기준)
imp_sbp = best_model_sbp.named_steps['randomforestregressor'].feature_importances_
imp_dbp = best_model_dbp.named_steps['randomforestregressor'].feature_importances_

imp_df_sbp = pd.DataFrame({'feature': CONFIG['feature_cols'], 'importance': imp_sbp}).sort_values('importance', ascending=False)
imp_df_dbp = pd.DataFrame({'feature': CONFIG['feature_cols'], 'importance': imp_dbp}).sort_values('importance', ascending=False)

sns.barplot(data=imp_df_sbp, x='importance', y='feature', ax=axes[2, 0], palette='Reds_r')
style_ax(axes[2, 0]); axes[2, 0].set_title('SBP Feature Importance')
style_ax(axes[2, 0])

sns.barplot(data=imp_df_dbp, x='importance', y='feature', ax=axes[2, 1], palette='Blues_r')
style_ax(axes[2, 1]); axes[2, 1].set_title('DBP Feature Importance')
style_ax(axes[2, 1])

plt.tight_layout()
plt.savefig('Final_Master_Report.png', dpi=300, bbox_inches='tight')
print("발표용 평가 리포트 시각화가 'Final_Master_Report.png'로 저장되었습니다!")
plt.show()

"""# 7. [최종] test 실전 예측 및 CSV 저장"""

from google.colab import files
uploaded = files.upload()

# 예측 구간

test_data_path = 'dataset(jump_60).csv'

if test_data_path is not None:
    try:
        test_data = pd.read_csv(test_data_path)

        # PAT, PTT가 다 채워져있어야 함. 없는 행 제거
        if 'PAT' in test_data.columns and 'PTT' in test_data.columns:
          test_data = test_data.dropna(subset=['PAT', 'PTT'])


        # 학습 데이터셋에 사용된 칼럼의 이름은 모두 테스트 데이터셋에 있어야함
        X_test = test_data[CONFIG['feature_cols']]

        sbp_preds = best_model_sbp.predict(X_test)
        dbp_preds = best_model_dbp.predict(X_test)

        def get_prediction_intervals(model_pipeline, X, percentile=95):

          # 파이프라인에서 스케일러와 랜덤포레스트 모델을 각각 분리해냄
          scaler = model_pipeline.named_steps['robustscaler']
          rf_model = model_pipeline.named_steps['randomforestregressor']

          # 테스트 데이터를 스케일러에 통과시킴 (predict 할 때 내부적으로 일어나는 과정 수동 재현)
          X_scaled = scaler.transform(X)

          # 숲에 있는 모든 나무(estimators)들에게 각각 예측을 시킴
          # all_tree_preds 형태: (나무 개수, 테스트 환자 수)
          all_tree_preds = np.array([tree.predict(X_scaled) for tree in rf_model.estimators_])

          # 95% 구간의 하한선(2.5%)과 상한선(97.5%) 계산
          lower_percentile = (100 - percentile) / 2.0
          upper_percentile = 100 - lower_percentile

          lower_bound = np.percentile(all_tree_preds, lower_percentile, axis=0)
          upper_bound = np.percentile(all_tree_preds, upper_percentile, axis=0)

          return lower_bound, upper_bound

        # 상/하한선 추출 실행
        sbp_lower, sbp_upper = get_prediction_intervals(best_model_sbp, X_test)
        dbp_lower, dbp_upper = get_prediction_intervals(best_model_dbp, X_test)


        final_results = pd.DataFrame({
            '예측_SBP': np.round(sbp_preds, 1),
            'SBP_하한선': np.round(sbp_lower, 1),
            'SBP_상한선': np.round(sbp_upper, 1),
            '예측_DBP': np.round(dbp_preds, 1),
            'DBP_하한선': np.round(dbp_lower, 1),
            'DBP_상한선': np.round(dbp_upper, 1)
        })

        # 기존 데이터의 식별자(ID 등)가 있다면 합쳐주면 더 좋음
        if 'subject_id' in test_data.columns:
          final_results = pd.concat([test_data['subject_id'].reset_index(drop=True), final_results], axis=1)
        else:
          dummy_ids = [f"Data_{i+1}" for i in range(len(final_results))]
          final_results.insert(0, 'subject_id', dummy_ids)
          print("\n[알림] 테스트 데이터에 'subject_id' 열이 없어 임시 ID(Data_1, Data_2...)를 자동 부여했습니다.")

        print("\n[실전 예측 완료] 예측 결과 및 상/하한선:")
        print(final_results.head())

        # 최종 결과 파일로 저장
        final_results.to_csv('final_submission_with_bounds.csv', index=False)
        print("\n'final_submission_with_bounds.csv' 파일이 성공적으로 저장되었습니다!")

    except FileNotFoundError:
        print(f"\n'{test_data_path}' 파일을 찾을 수 없습니다. 경로를 확인해주세요.")
else:
    print("\n[알림] 입력된 Test 파일이 없습니다. 모델 학습 및 모의고사 검증만 수행합니다.")