# -*- coding: utf-8 -*-
"""ELE- SVR모델 (찬미, 수빈 개발ing,,,)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Si6CZoxIPvjcSjTtEjXcBFawOIxxaX1s

# 진행상황
**3/25 수**

- 찬미님 코드 기반으로 진행
- 1차 수정- [찬미님 코드]에서 진행.

**3/26 목**

- 2차 수정- [수빈님 코드]에서 진행.
- 코드 정리 필요.
- sbp fail 예상요인: 스케일링 코드오류/ 데이터셋 상관계수 낮음

**5/07 목**
- 시우님 dataset으로 test완료.
- 코드 간소화 진행중
- 수빈코드(3차)/ 찬미코드(최종본) 으로 svr모델 완성.
- 다음주까지 게속 간소화 진행...

**5/21 목**
- 24개 dataset으로 코드 돌린 결과, 오차율 sbp 6.63%, dbp 12.09%
- test/train 0.8/0.2로 나누어 100번 random으로 돌리는 코드 추가완료.

**5/31 일**
- 시우님 데이터증강 알고리즘 적용중

## **최종 코드**
"""

# ============================================================
# Cell 1: 데이터 로드
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import warnings
warnings.filterwarnings('ignore')

from google.colab import files
uploaded = files.upload()
filename = list(uploaded.keys())[0]

dataset = pd.read_csv(filename)

print(dataset.head())


X = dataset.iloc[:, 1:7].values
y_sbp = dataset.iloc[:, 7].values

X_train, X_test, y_train_sbp, y_test_sbp = train_test_split(
    X, y_sbp, test_size=0.2, random_state=42
)

print(f"데이터: {len(dataset)}개 / 학습: {len(X_train)}개 / 테스트: {len(X_test)}개")
print(f"SBP 범위: {y_sbp.min():.1f} ~ {y_sbp.max():.1f}")
print(dataset.head())


# ============================================================
# Cell 2: 스케일링
# ============================================================

sc_X = StandardScaler()
X_train_scaled = sc_X.fit_transform(X_train)
X_test_scaled = sc_X.transform(X_test)

sc_sbp = StandardScaler()
y_train_sbp_scaled = sc_sbp.fit_transform(y_train_sbp.reshape(-1, 1)).ravel()

print("스케일링 완료!")


# ============================================================
# Cell 3: SBP 모델
# ============================================================

param_dist = {
    'C': np.logspace(-1, 3, 50),
    'epsilon': np.linspace(0.001, 0.2, 50),
    'gamma': np.logspace(-3, 0, 50)
}

random_sbp = RandomizedSearchCV(
    SVR(kernel='rbf'), param_dist,
    n_iter=50, cv=5, scoring='neg_mean_absolute_error',
    n_jobs=-1, random_state=42
)
random_sbp.fit(X_train_scaled, y_train_sbp_scaled)

y_sbp_pred = sc_sbp.inverse_transform(
    random_sbp.predict(X_test_scaled).reshape(-1, 1)
).ravel()

print(f"최적 파라미터: {random_sbp.best_params_}")
print(f"SBP MAE: {mean_absolute_error(y_test_sbp, y_sbp_pred):.2f} mmHg")
print(f"SBP R²:  {r2_score(y_test_sbp, y_sbp_pred):.4f}")


# ============================================================
# Cell 4: 성능 평가 (AAMI / BHS)
# ============================================================

errors = y_test_sbp - y_sbp_pred
mae = np.mean(np.abs(errors))
me = np.mean(errors)
std = np.std(errors)
rmse = np.sqrt(np.mean(errors**2))
r2 = r2_score(y_test_sbp, y_sbp_pred)

aami_pass = (abs(me) <= 5) and (std <= 8)

abs_e = np.abs(errors)
bhs_5 = np.mean(abs_e <= 5) * 100
bhs_10 = np.mean(abs_e <= 10) * 100
bhs_15 = np.mean(abs_e <= 15) * 100

if bhs_5 >= 60 and bhs_10 >= 85 and bhs_15 >= 95: grade = 'A'
elif bhs_5 >= 50 and bhs_10 >= 75 and bhs_15 >= 90: grade = 'B'
elif bhs_5 >= 40 and bhs_10 >= 65 and bhs_15 >= 85: grade = 'C'
else: grade = 'D'

print("=" * 50)
print("SBP 최종 성능")
print("=" * 50)
print(f"MAE: {mae:.2f} | ME: {me:.2f} | STD: {std:.2f} | RMSE: {rmse:.2f} | R²: {r2:.4f}")
print(f"AAMI: {'PASS' if aami_pass else 'FAIL'} | BHS: Grade {grade} (<=5: {bhs_5:.0f}%, <=10: {bhs_10:.0f}%, <=15: {bhs_15:.0f}%)")

# ============================================================
# Cell 5: 시각화
# ============================================================
plt.rcParams['font.family'] = 'DejaVu Sans'

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# 1. 실제값 vs 예측값
axes[0].scatter(y_test_sbp, y_sbp_pred, alpha=0.6, s=30, color='royalblue')
axes[0].plot([y_test_sbp.min(), y_test_sbp.max()],
             [y_test_sbp.min(), y_test_sbp.max()], 'r--', lw=2)
axes[0].set_xlabel('Actual SBP (mmHg)')
axes[0].set_ylabel('Predicted SBP (mmHg)')
axes[0].set_title(f'Actual vs Predicted (MAE: {mae:.2f})')
axes[0].grid(True, alpha=0.3)

# 2. 오차율 분포 히스토그램 (절대값)
error_rate = np.abs(errors / y_test_sbp) * 100
axes[1].hist(error_rate, bins=10, color='salmon', edgecolor='black', alpha=0.7)
axes[1].axvline(x=np.mean(error_rate), color='blue', linestyle='-', lw=2,
                label=f'Mean: {np.mean(error_rate):.2f}%')
axes[1].set_xlabel('Absolute Error Rate (%)')
axes[1].set_ylabel('Count')
axes[1].set_title(f'Error Rate Distribution (Mean: {np.mean(error_rate):.2f}%)')
axes[1].legend()
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

print(f"\n{'Actual':>8} {'Predicted':>10} {'Error':>6} {'Rate':>7}")
print("-" * 35)
for i in range(len(y_test_sbp)):
    err = abs(y_test_sbp[i] - y_sbp_pred[i])
    rate = (err / y_test_sbp[i]) * 100
    print(f"{y_test_sbp[i]:>8.1f} {y_sbp_pred[i]:>10.1f} {err:>5.1f} {rate:>6.1f}%")


# ============================================================
# Cell 6: 결과 CSV 저장
# ============================================================

result_df = pd.DataFrame({
    'Actual_SBP': y_test_sbp,
    'Predicted_SBP': y_sbp_pred,
    'Error': y_test_sbp - y_sbp_pred
})

result_df.to_csv('SBP_prediction_results.csv', index=False)

files.download('SBP_prediction_results.csv')

"""최종 코드"""

# ============================================================
# Cell 1: 데이터 로드 및 전처리 (수정본)
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import warnings
warnings.filterwarnings('ignore')

from google.colab import files

# ------------------------------------------------------------
# 1. CSV 업로드
# ------------------------------------------------------------

uploaded = files.upload()

filename = list(uploaded.keys())[0]

dataset = pd.read_csv(filename)

print(dataset.head())

# 불필요한 컬럼 제거
dataset = dataset.drop(
    columns=['subject_id', 'test_num', 'file'],
    errors='ignore'
)

print(dataset.head())

# 🔧 추가: 이미지 저장명 미리 생성
save_name = filename.replace('.csv', '') + '_result.png'

# ============================================================
# 2. 컬럼 이름 설정
# ============================================================

# 현재 CSV 기준
target_sbp = 'sbp (mmHg)'
target_dbp = 'dbp  (mmHg)'

# ------------------------------------------------------------
# feature 선택
# sbp/dbp 제외
# ------------------------------------------------------------

base_features = [
    col for col in dataset.columns
    if col not in [target_sbp, target_dbp]
]

print("\n사용 feature:")
print(base_features)

# ============================================================
# 3. IQR 이상치 제거
# ============================================================

numeric_cols = dataset.select_dtypes(include=np.number).columns

Q1 = dataset[numeric_cols].quantile(0.25)
Q3 = dataset[numeric_cols].quantile(0.75)

IQR = Q3 - Q1

dataset = dataset[
    ~((dataset[numeric_cols] < (Q1 - 1.5 * IQR)) |
      (dataset[numeric_cols] > (Q3 + 1.5 * IQR))).any(axis=1)
]

dataset = dataset.reset_index(drop=True)

print(f"\nIQR 이상치 제거 후 데이터 개수: {len(dataset)}")

# ============================================================
# 4. 물리적으로 불가능한 혈압 제거
# ============================================================

invalid = len(dataset[
    dataset[target_sbp] <= dataset[target_dbp]
])

print(f"\nSBP <= DBP 데이터 개수: {invalid}")

dataset = dataset[
    dataset[target_sbp] > dataset[target_dbp]
].reset_index(drop=True)

# ============================================================
# 5. 혈압 범위 필터링
# ============================================================

dataset = dataset[
    (dataset[target_sbp] < 200) &
    (dataset[target_dbp] > 40)
]

dataset = dataset.reset_index(drop=True)

print(f"\n최종 데이터 개수: {len(dataset)}")

# ============================================================
# 6. Feature / Label 구성
# ============================================================

# ------------------------------------------------------------
# DBP 예측용:
# SBP 포함
# ------------------------------------------------------------

X_total = dataset[
    base_features + [target_sbp]
].values

# label
y_sbp = dataset[target_sbp].values
y_dbp = dataset[target_dbp].values

# ============================================================
# 7. Train / Test Split
# ============================================================

X_train_total, X_test_total, \
y_train_sbp, y_test_sbp, \
y_train_dbp, y_test_dbp = train_test_split(
    X_total,
    y_sbp,
    y_dbp,
    test_size=0.2,
    random_state=42
)

# ============================================================
# 8. 모델별 입력 구성
# ============================================================

# ------------------------------------------------------------
# SBP 예측:
# sbp 제외
# ------------------------------------------------------------

X_train_sbp = X_train_total[:, :-1]
X_test_sbp = X_test_total[:, :-1]

# ------------------------------------------------------------
# DBP 예측:
# sbp 포함
# ------------------------------------------------------------

X_train_dbp = X_train_total
X_test_dbp = X_test_total

# ============================================================
# 결측값(NaN) 제거
# ============================================================

print(f"\n원본 데이터 개수: {len(dataset)}")

dataset = dataset.dropna().reset_index(drop=True)

print(f"결측값 제거 후 데이터 개수: {len(dataset)}")

print(dataset.head())



# ============================================================
# 9. 출력
# ============================================================

print("\n[데이터 분리 완료]")

print(f"학습 데이터 개수: {X_train_sbp.shape[0]}")
print(f"테스트 데이터 개수: {X_test_sbp.shape[0]}")

print(f"\nSBP 범위: {y_sbp.min():.1f} ~ {y_sbp.max():.1f}")
print(f"DBP 범위: {y_dbp.min():.1f} ~ {y_dbp.max():.1f}")

print(f"\nSBP 입력 shape: {X_train_sbp.shape}")
print(f"DBP 입력 shape: {X_train_dbp.shape}")

print("\n데이터 준비 완료!")

from sklearn.preprocessing import StandardScaler

# ============================================================
# 1. Feature(X) 스케일링
# ============================================================

scaler_X_sbp = StandardScaler()
scaler_X_dbp = StandardScaler()

# X_train_sbp: [PAT, PTT, weight, height, age, gender] → 그대로 사용
X_train_sbp_scaled = scaler_X_sbp.fit_transform(X_train_sbp)
X_test_sbp_scaled  = scaler_X_sbp.transform(X_test_sbp)

# X_train_dbp: [PAT, PTT, weight, height, age, gender, sbp] → 그대로 사용
X_train_dbp_scaled = scaler_X_dbp.fit_transform(X_train_dbp)
X_test_dbp_scaled  = scaler_X_dbp.transform(X_test_dbp)

# ============================================================
# 2. Target(y) 스케일링
# ============================================================

scaler_y_sbp = StandardScaler()
scaler_y_dbp = StandardScaler()

y_train_sbp_scaled = scaler_y_sbp.fit_transform(y_train_sbp.reshape(-1, 1)).ravel()
y_test_sbp_scaled  = scaler_y_sbp.transform(y_test_sbp.reshape(-1, 1)).ravel()

y_train_dbp_scaled = scaler_y_dbp.fit_transform(y_train_dbp.reshape(-1, 1)).ravel()
y_test_dbp_scaled  = scaler_y_dbp.transform(y_test_dbp.reshape(-1, 1)).ravel()

# ============================================================
# 3. 출력
# ============================================================

print("✅ 모든 Feature 및 Target 스케일링 완료!")
print("\n[SBP]")
print(f"X_train shape: {X_train_sbp_scaled.shape}")  # (N, 6)
print(f"X_test shape : {X_test_sbp_scaled.shape}")

print("\n[DBP]")
print(f"X_train shape: {X_train_dbp_scaled.shape}")  # (N, 7)
print(f"X_test shape : {X_test_dbp_scaled.shape}")

print("\nTarget Scaling 완료!")

# ============================================================
# Cell 3: SBP 모델 학습 (수정본)
# ============================================================

print("SBP 모델 학습 중...")

from sklearn.model_selection import RandomizedSearchCV
from sklearn.svm import SVR
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# ============================================================
# 1. SVR 모델 정의
# ============================================================

svr_sbp = SVR(kernel='rbf')

# ============================================================
# 2. 하이퍼파라미터 탐색 범위
# ============================================================

param_dist = {
    'C': np.logspace(-1, 3, 50),
    'epsilon': np.linspace(0.001, 0.2, 50),
    'gamma': np.logspace(-3, 0, 50)
}

# ============================================================
# 3. RandomizedSearchCV
# ============================================================

random_sbp = RandomizedSearchCV(
    estimator=svr_sbp,
    param_distributions=param_dist,
    n_iter=50,
    cv=5,
    scoring='neg_mean_absolute_error',
    n_jobs=-1,
    random_state=42
)

# ============================================================
# 4. 모델 학습
# ============================================================

# NaN/Inf 값 처리 (SVR이 NaN/Inf 값을 허용하지 않으므로 변환)
X_train_sbp_scaled_finite = np.nan_to_num(X_train_sbp_scaled)
y_train_sbp_scaled_finite = np.nan_to_num(y_train_sbp_scaled)

random_sbp.fit(
    X_train_sbp_scaled_finite,
    y_train_sbp_scaled_finite
)

# ============================================================
# 5. 최적 모델 저장
# ============================================================

best_svr_sbp = random_sbp.best_estimator_

# ============================================================
# 6. 예측
# ============================================================

# 테스트 데이터도 NaN/Inf 값 처리
X_test_sbp_scaled_finite = np.nan_to_num(X_test_sbp_scaled)

y_sbp_pred_scaled = best_svr_sbp.predict(
    X_test_sbp_scaled_finite
)

# 역스케일링
y_sbp_pred = scaler_y_sbp.inverse_transform(
    y_sbp_pred_scaled.reshape(-1, 1)
).ravel()

# ============================================================
# 7. 성능 평가
# ============================================================

mae = mean_absolute_error(
    y_test_sbp,
    y_sbp_pred
)

rmse = np.sqrt(
    mean_squared_error(
        y_test_sbp,
        y_sbp_pred
    )
)

r2 = r2_score(
    y_test_sbp,
    y_sbp_pred
)

# ============================================================
# 8. 결과 출력
# ============================================================

print("\n===== SBP 결과 ====")

print(f"최적 파라미터:")
print(random_sbp.best_params_)

print(f"\nMAE  : {mae:.2f} mmHg")
print(f"RMSE : {rmse:.2f} mmHg")
print(f"R²   : {r2:.4f}")

print(dataset.columns.tolist())
print(dataset.dtypes)

# ============================================================
# Cell 4: SBP 반복 검증
# ============================================================

print("\nSBP 반복 검증 시작...")

import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# ============================================================
# 전체 SBP 데이터 구성
# ============================================================

# Re-create feature_cols_for_selection based on current dataset columns
# to exclude target columns (sbp, dbp). The 'file' column is already
# dropped from 'dataset' by a previously executed cell.
feature_cols_for_selection = [
    col for col in dataset.columns
    if col not in [target_sbp, target_dbp]
]

X_sbp_total = dataset[feature_cols_for_selection].values
y_sbp_total = dataset[target_sbp].values

# ============================================================
# 반복 횟수
# ============================================================

N_REPEAT = 100

# ============================================================
# 결과 저장
# ============================================================

mae_list = []
rmse_list = []
r2_list = []

# ============================================================
# 반복 시작
# ============================================================

for i in range(N_REPEAT):

    # --------------------------------------------------------
    # 1. 랜덤 8:2 분할
    # --------------------------------------------------------

    X_train, X_test, y_train, y_test = train_test_split(
        X_sbp_total,
        y_sbp_total,
        test_size=0.2,
        shuffle=True,
        random_state=None
    )

    # --------------------------------------------------------
    # 2. Scaling
    # --------------------------------------------------------

    scaler_X = StandardScaler()
    scaler_y = StandardScaler()

    X_train_scaled = scaler_X.fit_transform(X_train)
    X_test_scaled = scaler_X.transform(X_test)

    y_train_scaled = scaler_y.fit_transform(
        y_train.reshape(-1,1)
    ).ravel()

    # --------------------------------------------------------
    # 3. 최적 파라미터 적용
    # --------------------------------------------------------

    svr = SVR(
        kernel='rbf',
        C=random_sbp.best_params_['C'],
        gamma=random_sbp.best_params_['gamma'],
        epsilon=random_sbp.best_params_['epsilon']
    )

    # --------------------------------------------------------
    # 4. 학습
    # --------------------------------------------------------

    svr.fit(X_train_scaled, y_train_scaled)

    # --------------------------------------------------------
    # 5. 예측
    # --------------------------------------------------------

    y_pred_scaled = svr.predict(X_test_scaled)

    y_pred = scaler_y.inverse_transform(
        y_pred_scaled.reshape(-1,1)
    ).ravel()

    # --------------------------------------------------------
    # 6. 성능 평가
    # --------------------------------------------------------

    mae = mean_absolute_error(y_test, y_pred)

    rmse = np.sqrt(
        mean_squared_error(y_test, y_pred)
    )

    r2 = r2_score(y_test, y_pred)

    # --------------------------------------------------------
    # 7. 저장
    # --------------------------------------------------------

    mae_list.append(mae)
    rmse_list.append(rmse)
    r2_list.append(r2)

    print(f"[{i+1}/{N_REPEAT}] "
          f"MAE={mae:.2f}, "
          f"RMSE={rmse:.2f}, "
          f"R²={r2:.4f}")

# ============================================================
# 최종 결과
# ============================================================

print("\n===== SBP 평균 성능 ====")

print(f"Average MAE  : {np.mean(mae_list):.2f} mmHg")
print(f"Average RMSE : {np.mean(rmse_list):.2f} mmHg")
print(f"Average R²   : {np.mean(r2_list):.4f}")

print("\n===== 표준편차 ====")

print(f"MAE std  : {np.std(mae_list):.2f}")
print(f"RMSE std : {np.std(rmse_list):.2f}")
print(f"R² std   : {np.std(r2_list):.4f}")

print("\nDBP 모델 학습 중...")

from sklearn.model_selection import RandomizedSearchCV
from sklearn.svm import SVR
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# ============================================================
# 2. SVR 모델 정의
# ============================================================

svr_dbp = SVR(kernel='rbf')

# ============================================================
# 3. 하이퍼파라미터 범위
# ============================================================

param_dist = {
    'C': np.logspace(-1, 3, 50),
    'epsilon': np.linspace(0.001, 0.2, 50),
    'gamma': np.logspace(-3, 0, 50)
}

# ============================================================
# 4. RandomizedSearchCV
# ============================================================

random_dbp = RandomizedSearchCV(
    estimator=svr_dbp,
    param_distributions=param_dist,
    n_iter=50,
    cv=5,
    scoring='neg_mean_absolute_error',
    n_jobs=-1,
    random_state=42
)

# ============================================================
# 5. 모델 학습
# ============================================================

# NaN/Inf 값 처리 (SVR이 NaN/Inf 값을 허용하지 않으므로 변환)
X_train_dbp_scaled_finite = np.nan_to_num(X_train_dbp_scaled)
y_train_dbp_scaled_finite = np.nan_to_num(y_train_dbp_scaled)

random_dbp.fit(
    X_train_dbp_scaled_finite,
    y_train_dbp_scaled_finite
)

# ============================================================
# 6. 최적 모델 저장
# ============================================================

best_svr_dbp = random_dbp.best_estimator_

# ============================================================
# 7. 예측
# ============================================================

# 테스트 데이터도 NaN/Inf 값 처리
X_test_dbp_scaled_finite = np.nan_to_num(X_test_dbp_scaled)

y_dbp_pred_scaled = best_svr_dbp.predict(
    X_test_dbp_scaled_finite
)

# 역스케일링
y_dbp_pred = scaler_y_dbp.inverse_transform(
    y_dbp_pred_scaled.reshape(-1, 1)
).ravel()

# ============================================================
# 8. 성능 평가
# ============================================================

mae = mean_absolute_error(
    y_test_dbp,
    y_dbp_pred
)

rmse = np.sqrt(
    mean_squared_error(
        y_test_dbp,
        y_dbp_pred
    )
)

r2 = r2_score(
    y_test_dbp,
    y_dbp_pred
)

# ============================================================
# 9. 결과 출력
# ============================================================

print("\n===== DBP 결과 ====")

print(f"최적 파라미터:")
print(random_dbp.best_params_)

print(f"\nMAE  : {mae:.2f} mmHg")
print(f"RMSE : {rmse:.2f} mmHg")
print(f"R²   : {r2:.4f}")

print(f"\nBest CV MAE : {-random_dbp.best_score_:.2f}")

# ============================================================
# Cell 5: DBP 반복 검증
# ============================================================

print("\nDBP 반복 검증 시작...")

import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)
from sklearn.svm import SVR

# ============================================================
# 전체 DBP 데이터 구성
# ============================================================

# DBP는 SBP 포함해서 예측
X_dbp_total = dataset[
    [col for col in dataset.columns if col != target_dbp]
].values

y_dbp_total = dataset[target_dbp].values

# ============================================================
# 반복 횟수
# ============================================================

N_REPEAT = 100

# ============================================================
# 결과 저장 리스트
# ============================================================

mae_list = []
rmse_list = []
r2_list = []

# ============================================================
# 반복 시작
# ============================================================

for i in range(N_REPEAT):

    # --------------------------------------------------------
    # 1. 랜덤 8:2 분할
    # --------------------------------------------------------

    X_train, X_test, y_train, y_test = train_test_split(
        X_dbp_total,
        y_dbp_total,
        test_size=0.2,
        shuffle=True,
        random_state=None
    )

    # --------------------------------------------------------
    # 2. Scaling
    # --------------------------------------------------------

    scaler_X = StandardScaler()
    scaler_y = StandardScaler()

    # 'subject_id' 컬럼 제외하고 스케일링
    X_train_scaled = scaler_X.fit_transform(X_train[:, 1:])
    X_test_scaled = scaler_X.transform(X_test[:, 1:])

    y_train_scaled = scaler_y.fit_transform(
        y_train.reshape(-1,1)
    ).ravel()

    # --------------------------------------------------------
    # 3. 최적 파라미터 적용
    # --------------------------------------------------------

    svr = SVR(
        kernel='rbf',
        C=random_dbp.best_params_['C'],
        gamma=random_dbp.best_params_['gamma'],
        epsilon=random_dbp.best_params_['epsilon']
    )

    # --------------------------------------------------------
    # 4. 학습
    # --------------------------------------------------------

    # NaN/Inf 값 처리 (SVR이 NaN/Inf 값을 허용하지 않으므로 변환)
    X_train_scaled_finite = np.nan_to_num(X_train_scaled)
    y_train_scaled_finite = np.nan_to_num(y_train_scaled)

    svr.fit(X_train_scaled_finite, y_train_scaled_finite)

    # --------------------------------------------------------
    # 5. 예측
    # --------------------------------------------------------

    # 테스트 데이터도 NaN/Inf 값 처리
    X_test_scaled_finite = np.nan_to_num(X_test_scaled)

    y_pred_scaled = svr.predict(X_test_scaled_finite)

    y_pred = scaler_y.inverse_transform(
        y_pred_scaled.reshape(-1,1)
    ).ravel()

    # --------------------------------------------------------
    # 6. 성능 평가
    # --------------------------------------------------------

    mae = mean_absolute_error(y_test, y_pred)

    rmse = np.sqrt(
        mean_squared_error(y_test, y_pred)
    )

    r2 = r2_score(y_test, y_pred)

    # --------------------------------------------------------
    # 7. 저장
    # --------------------------------------------------------

    mae_list.append(mae)
    rmse_list.append(rmse)
    r2_list.append(r2)

    print(f"[{i+1}/{N_REPEAT}] "
          f"MAE={mae:.2f}, "
          f"RMSE={rmse:.2f}, "
          f"R²={r2:.4f}")

# ============================================================
# 최종 결과 출력
# ============================================================

print("\n===== DBP 평균 성능 ====")

print(f"Average MAE  : {np.mean(mae_list):.2f} mmHg")
print(f"Average RMSE : {np.mean(rmse_list):.2f} mmHg")
print(f"Average R²   : {np.mean(r2_list):.4f}")

print("\n===== 표준편차 ====")

print(f"MAE std  : {np.std(mae_list):.2f}")
print(f"RMSE std : {np.std(rmse_list):.2f}")
print(f"R² std   : {np.std(r2_list):.4f}")

# ============================================================
# Cell 5: SBP-DBP 관계 검증
# ============================================================

print("=" * 60)
print("SBP-DBP 관계 검증")
print("=" * 60)

# ============================================================
# 1. Pulse Pressure 계산
# ============================================================

# 실제 PP
pp_actual = y_test_sbp - y_test_dbp

# 예측 PP
pp_pred = y_sbp_pred - y_dbp_pred

# ============================================================
# 3. Pulse Pressure 정상 범위 검사
# ============================================================

# 일반적인 정상 범위: 30~60 mmHg
pp_normal = np.sum(
    (pp_pred >= 30) &
    (pp_pred <= 60)
)

pp_ratio = pp_normal / len(pp_pred) * 100

print(f"\n[Pulse Pressure 검사]")
print(f"정상 범위(30~60 mmHg) 비율 : {pp_ratio:.1f}%")

print(f"평균 PP (실제) : {np.mean(pp_actual):.2f}")
print(f"평균 PP (예측) : {np.mean(pp_pred):.2f}")

# ============================================================
# 4. MAP 계산
#    MAP = DBP + (PP / 3)
# ============================================================

map_actual = (
    y_test_dbp +
    (y_test_sbp - y_test_dbp) / 3
)

map_pred = (
    y_dbp_pred +
    (y_sbp_pred - y_dbp_pred) / 3
)

# ============================================================
# 5. MAP 성능 평가
# ============================================================

map_mae = mean_absolute_error(
    map_actual,
    map_pred
)

map_rmse = np.sqrt(
    mean_squared_error(
        map_actual,
        map_pred
    )
)

print(f"\n[MAP 평가]")
print(f"MAP MAE  : {map_mae:.2f} mmHg")
print(f"MAP RMSE : {map_rmse:.2f} mmHg")

print("\n검증 완료!")

# ============================================================
# Cell 6: 성능 평가 (AAMI / BHS 국제 가이드라인)
# ============================================================

def evaluate(y_true, y_pred, label):
    errors = np.array(y_true) - np.array(y_pred)
    mae = np.mean(np.abs(errors))
    me = np.mean(errors)
    std = np.std(errors)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)

    # AAMI 기준: 오차평균 <= 5, 오차표준편차 <= 8
    aami_pass = (abs(me) <= 5) and (std <= 8)

    # BHS 기준
    abs_errors = np.abs(errors)
    bhs_5 = np.mean(abs_errors <= 5) * 100
    bhs_10 = np.mean(abs_errors <= 10) * 100
    bhs_15 = np.mean(abs_errors <= 15) * 100

    if bhs_5 >= 60 and bhs_10 >= 85 and bhs_15 >= 95:
        bhs_grade = 'A'
    elif bhs_5 >= 50 and bhs_10 >= 75 and bhs_15 >= 90:
        bhs_grade = 'B'
    elif bhs_5 >= 40 and bhs_10 >= 65 and bhs_15 >= 85:
        bhs_grade = 'C'
    else:
        bhs_grade = 'D'

    print(f"\n--- {label} ---")
    print(f"  MAE:  {mae:.2f} mmHg")
    print(f"  ME:   {me:.2f} mmHg")
    print(f"  STD:  {std:.2f} mmHg")
    print(f"  RMSE: {rmse:.2f} mmHg")
    print(f"  R²:   {r2:.4f}")
    print(f"  AAMI: {'PASS' if aami_pass else 'FAIL'} (기준: ME<=5, STD<=8)")
    print(f"  BHS:  Grade {bhs_grade} (<=5: {bhs_5:.1f}%, <=10: {bhs_10:.1f}%, <=15: {bhs_15:.1f}%)")

print("=" * 50)
print("SVR (RBF kernel + GridSearchCV) 최종 성능")
print("=" * 50)

evaluate(y_test_sbp, y_sbp_pred, "SBP (수축기 혈압)")
evaluate(y_test_dbp, y_dbp_pred, "DBP (이완기 혈압)")

# ============================================================
# Cell 7: 결과 시각화 및 샘플 출력
# ============================================================

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import numpy as np
import matplotlib.pyplot as plt

# ============================================================
# 1. 성능 계산
# ============================================================

sbp_mae = mean_absolute_error(
    y_test_sbp,
    y_sbp_pred
)

dbp_mae = mean_absolute_error(
    y_test_dbp,
    y_dbp_pred
)

sbp_r2 = r2_score(
    y_test_sbp,
    y_sbp_pred
)

dbp_r2 = r2_score(
    y_test_dbp,
    y_dbp_pred
)

# ============================================================
# 2. 오차율 계산
# ============================================================

# 절대 오차
sbp_errors = np.abs(y_test_sbp - y_sbp_pred)
dbp_errors = np.abs(y_test_dbp - y_dbp_pred)

# 오차율(%)
sbp_error_rate = (sbp_errors / y_test_sbp) * 100
dbp_error_rate = (dbp_errors / y_test_dbp) * 100

# ============================================================
# 3. 시각화
# ============================================================

plt.rcParams['font.family'] = 'DejaVu Sans'

fig, axes = plt.subplots(
    2, 2,
    figsize=(14, 10)
)

# ============================================================
# [1] SBP 실제값 vs 예측값
# ============================================================

axes[0, 0].scatter(
    y_test_sbp,
    y_sbp_pred,
    alpha=0.7,
    s=40,
    color='royalblue'
)

min_sbp = min(y_test_sbp.min(), y_sbp_pred.min())
max_sbp = max(y_test_sbp.max(), y_sbp_pred.max())

axes[0, 0].plot(
    [min_sbp, max_sbp],
    [min_sbp, max_sbp],
    'r--',
    lw=2
)

axes[0, 0].set_xlabel('Actual SBP (mmHg)')
axes[0, 0].set_ylabel('Predicted SBP (mmHg)')

axes[0, 0].set_title(
    f'SBP Prediction\n'
    f'MAE={sbp_mae:.2f}, R²={sbp_r2:.3f}'
)

axes[0, 0].grid(True, alpha=0.3)

# ============================================================
# [2] SBP 오차율 히스토그램
# ============================================================

axes[0, 1].hist(
    sbp_error_rate,
    bins=10,
    color='salmon',
    edgecolor='black',
    alpha=0.7
)

axes[0, 1].axvline(
    x=np.mean(sbp_error_rate),
    color='blue',
    linestyle='-',
    lw=2,
    label=f'Mean: {np.mean(sbp_error_rate):.2f}%'
)

axes[0, 1].set_xlabel('SBP Absolute Error Rate (%)')
axes[0, 1].set_ylabel('Count')

axes[0, 1].set_title(
    f'SBP Error Rate Distribution\n'
    f'Mean={np.mean(sbp_error_rate):.2f}%'
)

axes[0, 1].legend()
axes[0, 1].grid(True, alpha=0.3)

# ============================================================
# [3] DBP 실제값 vs 예측값
# ============================================================

axes[1, 0].scatter(
    y_test_dbp,
    y_dbp_pred,
    alpha=0.7,
    s=40,
    color='green'
)

min_dbp = min(y_test_dbp.min(), y_dbp_pred.min())
max_dbp = max(y_test_dbp.max(), y_dbp_pred.max())

axes[1, 0].plot(
    [min_dbp, max_dbp],
    [min_dbp, max_dbp],
    'r--',
    lw=2
)

axes[1, 0].set_xlabel('Actual DBP (mmHg)')
axes[1, 0].set_ylabel('Predicted DBP (mmHg)')

axes[1, 0].set_title(
    f'DBP Prediction\n'
    f'MAE={dbp_mae:.2f}, R²={dbp_r2:.3f}'
)

axes[1, 0].grid(True, alpha=0.3)

# ============================================================
# [4] DBP 오차율 히스토그램
# ============================================================

axes[1, 1].hist(
    dbp_error_rate,
    bins=10,
    color='orange',
    edgecolor='black',
    alpha=0.7
)

axes[1, 1].axvline(
    x=np.mean(dbp_error_rate),
    color='blue',
    linestyle='-',
    lw=2,
    label=f'Mean: {np.mean(dbp_error_rate):.2f}%'
)

axes[1, 1].set_xlabel('DBP Absolute Error Rate (%)')
axes[1, 1].set_ylabel('Count')

axes[1, 1].set_title(
    f'DBP Error Rate Distribution\n'
    f'Mean={np.mean(dbp_error_rate):.2f}%'
)

axes[1, 1].legend()
axes[1, 1].grid(True, alpha=0.3)

plt.tight_layout()

plt.savefig(save_name, dpi=150, bbox_inches='tight')
print(f"결과 이미지 저장 완료: {save_name}")

plt.show()

from google.colab import files
files.download(save_name)

# ============================================================
# 4. 샘플 예측 출력
# ============================================================

print("\n" + "=" * 90)
print("샘플 예측 비교")
print("=" * 90)

print(
    f"{'Actual SBP':>12} "
    f"{'Pred SBP':>12} "
    f"{'Error%':>10} │ "
    f"{'Actual DBP':>12} "
    f"{'Pred DBP':>12} "
    f"{'Error%':>10}"
)

print("-" * 90)

sample_n = min(10, len(y_test_sbp))

for i in range(sample_n):

    sbp_rate = (
        abs(y_test_sbp[i] - y_sbp_pred[i])
        / y_test_sbp[i]
    ) * 100

    dbp_rate = (
        abs(y_test_dbp[i] - y_dbp_pred[i])
        / y_test_dbp[i]
    ) * 100

    print(
        f"{y_test_sbp[i]:>12.1f} "
        f"{y_sbp_pred[i]:>12.1f} "
        f"{sbp_rate:>9.1f}% │ "
        f"{y_test_dbp[i]:>12.1f} "
        f"{y_dbp_pred[i]:>12.1f} "
        f"{dbp_rate:>9.1f}%"
    )

# ============================================================
# Cell 10: 단일 샘플 예측 (SBP만)
# ============================================================

from google.colab import files
import pandas as pd
import numpy as np

# ============================================================
# 1. 예측용 CSV 업로드
# ============================================================

print("예측할 데이터 CSV를 업로드하세요.\n")

uploaded_pred = files.upload()
pred_filename = list(uploaded_pred.keys())[0]

sample_df = pd.read_csv(pred_filename)

sample_df = sample_df.drop(
    columns=['subject_id', 'test_num', 'file', target_sbp, target_dbp],
    errors='ignore'
)

print(f"\n입력 데이터:")
print(sample_df)

# ============================================================
# 2. feature 순서 맞추기
# ============================================================

missing = [col for col in base_features if col not in sample_df.columns]
if missing:
    raise ValueError(f"CSV에 누락된 feature가 있습니다: {missing}")

sample = sample_df[base_features].values   # shape: (1, 6)

if np.isnan(sample).any():
    raise ValueError(f"입력 데이터에 NaN이 있습니다:\n{sample_df[base_features].isnull().sum()}")

# ============================================================
# 3. SBP 예측
# ============================================================

sample_sbp_scaled = scaler_X_sbp.transform(sample)
sbp_pred_scaled   = best_svr_sbp.predict(sample_sbp_scaled)
sbp_pred = scaler_y_sbp.inverse_transform(
    sbp_pred_scaled.reshape(-1, 1)
).ravel()[0]

# ============================================================
# 4. 결과 출력
# ============================================================

print("\n" + "=" * 40)
print("       혈압 예측 결과")
print("=" * 40)
print(f"  SBP : {sbp_pred:.1f} mmHg")
print("=" * 40)

# 혈압 분류 (JNC 기준)
if sbp_pred < 120:
    grade = "정상 (Normal)"
elif sbp_pred < 130:
    grade = "주의 혈압 (Elevated)"
elif sbp_pred < 140:
    grade = "고혈압 1기 (Stage 1)"
else:
    grade = "고혈압 2기 (Stage 2)"

print(f"  분류: {grade}")
print("=" * 40)